server:
  port: 8090
tengxun:
  accessKey: xxxxxxxxxxxxxxxxxxxx
  secretKey: xxxxxxxxxxxxxxxxxxxx
  bucket: xxxxxx-xxxxx
  bucketName: xxxxx-xxxxx
  path: https://xxxxx-xxxxx.cos.ap-xxxxx.myqcloud.com
  qianzhui: xxxxx

qiniu:
  accessKey: xxxxx-xxxxx
  secretKey: xxxxx-xxxxx
  bucketName: xxxxx-xxxxx
  prefix: dbblog
  domainOfBucket: http://img.cdn.xxxxx.xxxxx
spring:
  datasource:

    url: jdbc:mysql://127.0.0.1:3306/jladmin?serverTimezone=UTC&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: xxxxx
    password: xxxxx
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver

  # 邮箱配置
  mail:
    default-encoding: UTF-8
    #根据邮箱服务器 smtp.xx.com
    host: smtp.exmail.qq.com
    #发送者的邮箱账号
    username: xxxxx@xxxxx.com
    #发送者的邮箱密码 qq为授权码
    password: xxxxx
    port: 465

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false

mybatis-plus:
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 此处有坑 单模块加载也需要配置*(classpath 紧挨着的星) 解决自定义SQL无法执行
  mapper-locations: classpath*:mapper/*/*Mapper.xml
  global-config:
#    xml热更新是否开启
    refresh: true
    #主键类型 AUTO(0, "数据库ID自增"),
      #INPUT(1, "用户输入ID"),
      #ID_WORKER(2, "全局唯一ID"),
      #UUID(3, "全局唯一ID"),
    #NONE(4, "该类型为未设置主键类型"),
    #ID_WORKER_STR(5, "字符串全局唯一ID");
    db-config:
      id-type: auto
      field-strategy: not_empty




